service: aws-rust-test
provider:
  name: aws
  runtime: rust
  memorySize: 128
  stage: dev
  region: eu-north-1
  lambdaHashingVersion: 20201221

  environment:
    IMAGE_BUCKET: ${self:service}-image-bucket-${self:provider.stage}
    IMAGE_TABLE: ${self:service}-image-table-${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:ListBucket
          Resource: arn::s3bucket:#{AWS::Region}:#{AWS::AccountId}:bucket/${self:provider.environment.IMAGE_BUCKET}

        - Effect: "Allow"
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn::dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.IMAGE_TABLE}

  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-rust
  - serverless-pseudo-parameters

custom:
  rust:
    dockerless: false

package:
  individually: true

functions:
  uploader:
    handler: uploader
    events:
      - http:
          path: /
          method: post

  downloader:
    handler: downloader
    events:
      - http:
          path: /{id}
          method: get

  resizer:
    handler: resizer
    events:
      - s3:
          bucket: ${self:provider.environment.IMAGE_BUCKET}
          event: s3:ObjectCreated:*

resources:
  Resources:
    ImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.IMAGE_BUCKET}

    ImageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.IMAGE_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
