name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Musl
        run: rustup target add x86_64-unknown-linux-musl
      - name: Run clippy
        run: cargo clippy --all-targets -- -D clippy::all
      - name: Run tests
        run: cargo test --verbose --all

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Musl
        run: rustup target add x86_64-unknown-linux-musl
      - name: Run Build
        run: cargo build --verbose --all --release

  Deploy:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        if: env.AWS_ACCESS_KEY_ID && env.AWS_SECRET_ACCESS_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
          #STAGE: prod
        run: |
          npm install
          npx serverless deploy --conceal
